let simonSequence = [];
let playerSequence = [];

const directions = ["Up", "Down", "Left", "Right"];

//Declaring and setting up start and reset buttons

const gameStartButton = document.getElementById("GameStart");
const gameResetButton = document.getElementById("GameReset");

gameStartButton.addEventListener("click", function () {

    resetPlayerInput(); // resetPlayerInput() function called from below
    displayPlayerInput();

    gameStartFunction(); // gameStart function called from below
})

gameResetButton.addEventListener("click", function () {

    resetPlayerInput(); // resetPlayerInput() function called from below
    displayPlayerInput();
})



//Declaring and setting up player buttons

const buttonUp = document.getElementById("ButtonUp");
const buttonDown = document.getElementById("ButtonDown");
const buttonRight = document.getElementById("ButtonRight");
const buttonLeft = document.getElementById("ButtonLeft");

const playerInputDiv = document.getElementById("playerInput");

buttonUp.addEventListener("click", function () {
    playerSequence.push("Up"); //My guess is that .push basically means display?
    displayPlayerInput(); // displayPlayerInput function called from below
})

buttonDown.addEventListener("click", function () {
    playerSequence.push("Down");
    displayPlayerInput(); // displayPlayerInput function called from below
})

buttonRight.addEventListener("click", function () {
    playerSequence.push("Right");
    displayPlayerInput(); // displayPlayerInput function called from below
})

buttonLeft.addEventListener("click", function () {
    playerSequence.push("Left");
    displayPlayerInput(); // displayPlayerInput function called from below
})

//functions//

function gameStartFunction() {
    //this function will start the game
    // I will add functions such starting Simon's sequence

    simonSequence = []; //reset if game restarted

    for (let i = 0; i < 3; i++) {
        const randomIndex = Math.floor(Math.random() * directions.length);
        simonSequence.push(directions[randomIndex]);
    } 

    /*from what I understand , the let (let i = 0; i < 3; i++) basically means
      that it will loop 3 times, 3 directions for the player to input
      randomIndex is just generated by using Math.floor (Math.random() * directions.length)
      basically it means that that randomIndex will choose randomly between the four direction?*/

    console.log("Simon says:", simonSequence) //debug display
    displaySimonSequence(); //calls the displaySimonSequence below
}

function displaySimonSequence() {
    const simonInstruction = document.getElementById("simonInstruction");
    //this basically connects simonInstruction from js to the id= "simonInstuction" in html
    simonInstruction.innerHTML = "<p>Simon Says: " + simonSequence.join(" ") + "</p>";
    //innerHTML connection so simonInstruction can manipulate the HTML DOM
}


function displayPlayerInput() {
    //this function will show what the user has input so far
    playerInputDiv.innerHTML = "<p>Your input: " + playerSequence.join(" ") + "</p>";

    //playerInputDiv.innetHTML basically means that this function is able to access html divs
    //playerSequence.join(" ") is for displaying the player sequence along with a space in the middle
}

function resetPlayerInput() {
    //this function will reset the player input
    // it empties the array back to playerSequence = [];
    playerSequence = [];

}